Accessibilty improvements to modals
cryptpad/cryptpad pull request #1563
Opened 2024-07-12 13:38 UTC by davidbenque

This PR aims to fix the following issues

- [ ] #1537 
- [ ] #1561

2024-07-23 13:30 UTC, yflory requested changes

2024-07-24 09:05 UTC, dariiing commented on www/calendar/app-calendar.less
> +                    outline: @cryptpad_color_brand solid 2px;
I followed the original behavior of this button: you can click anywhere on the div and get the same result; but I agree it's a bit weird

2024-07-24 09:39 UTC, dariiing commented on www/calendar/inner.js
> +            UI.addTabListener(el);
fixed in https://github.com/cryptpad/cryptpad/pull/1563/commits/6ed9ea3fa331d9ab4107d7271adb7029cbca30c9

2024-07-24 11:33 UTC, dariiing commented on www/common/common-interface.js
> +            addTabListener(frame);
These are the 3 scenarios that I tested:
- focus is on the "Cancel" button and I press the Enter key, the Cancel button triggers
- focus is on the "OK" button and I press the Enter key, the OK button triggers
-  focus is on the name input and I press Enter, the OK button triggers (the same functionality has been tested on prod)
- focus is on the name input and I press Esc, the Cancel button triggers (also tested on prod).
Should I make the Esc work anywhere?

2024-07-25 09:44 UTC, davidbenque commented on www/calendar/app-calendar.less
> +                    outline: @cryptpad_color_brand solid 2px;
After discussion we agreed to keep the same behaviour as the mouse interaction which highlights the whole "row" on hover

2024-07-25 11:42 UTC, yflory approved these changes

2024-08-28 15:06 UTC, merged