Make password change confirmation button responsive on mobile
cryptpad/cryptpad pull request #1569
Opened 2024-07-17 14:48 UTC by DianaXWiki

2024-07-18 14:49 UTC, davidbenque requested changes

2024-07-18 14:49 UTC, davidbenque commented on customize.dist/src/less2/include/alertify.less
> +                align-items: center;
The level of this change is way too high. All `nav` in modals are affected, check for example the Share modal

2024-07-30 10:52 UTC, davidbenque approved these changes
Pending some checks on scoping (see comments) and testing of the install page confirm button which I did not do.

2024-07-30 10:52 UTC, davidbenque commented on customize.dist/src/less2/pages/page-install.less
in case `.btn-danger` was used elsewhere in page-install, it now does not get styles that it used to. To check that the confirm button is indeed the only button that this was used for

2024-07-30 10:52 UTC, davidbenque commented on customize.dist/src/less2/pages/page-register.less
in case `.btn-danger` was used elsewhere in page-install, it now does not get styles that it used to. To check that the confirm button is indeed the only button that this was used for

2024-07-30 10:52 UTC, davidbenque commented on www/common/common-interface.js
> +        console.log('Parameters:', { msg, cb, opt, force, className });
logging should be removed

2024-07-30 10:52 UTC, davidbenque commented on www/settings/app-settings.less
> +        nav {
This affects all buttons navs in modals in settings. potentially some unintended consequences

2024-07-30 10:52 UTC, davidbenque commented on www/settings/app-settings.less
> +            nav {
check scoping

2024-07-30 11:07 UTC, davidbenque commented
![image](https://github.com/user-attachments/assets/1ec39971-dd29-4f63-893f-f76dd057ad4f)

The buttons should be aligned to the right side here. This used to be done with `text-align` but could also be done with a flex propoerty

2024-07-31 09:43 UTC, Chouhartem commented
Small screens in landscape (on firefox responsive design mode) don’t trigger the `@media` and let the button overflow:

![screenshot_responsive](https://github.com/user-attachments/assets/1b832f1f-9e79-4e6b-9b52-24c71357fd14)

2024-08-22 13:53 UTC, davidbenque commented
👍🏻 this looks better from the UI side

2024-08-26 12:41 UTC, yflory approved these changes

2024-09-09 11:24 UTC, merged