Fix emoji avatar handling and team name overflowing in sidebar teams
cryptpad/cryptpad pull request #1598
Opened 2024-08-16 13:32 UTC by DianaXWiki

2024-08-29 13:27 UTC, davidbenque commented
👍🏻 looks OK at first UI check. Needs review of code and use of regex

2024-09-02 15:01 UTC, yflory requested changes

2024-09-02 15:01 UTC, yflory commented on www/common/inner/common-mediatag.js
> +    const emojiWithZWJRegex = /(\p{Emoji_Presentation}|\p{Emoji_Modifier_Base})(\p{Emoji_Modifier})?(?:\u200D(\p{Emoji_Presentation}|\p{Emoji_Modifier_Base})(\p{Emoji_Modifier})?)*/gu;
When using complex regex such as this one, please add a comment about what it does :)
FYI it seems this regex doesn't work in some cases from https://www.unicode.org/Public/emoji/latest/emoji-zwj-sequences.txt (the emoji is split with the regex). e.g. 🧑🏿‍❤️‍💋‍🧑🏽

2024-09-02 15:01 UTC, yflory commented on www/common/inner/common-mediatag.js
> +            name = name.replace(/[\uFE0F\u200D\u2060]/g, '');
Same here, a small comment about what this is supposed to do please

2024-09-04 13:36 UTC, yflory approved these changes

2024-09-09 11:27 UTC, merged