Contact request notification fixes
cryptpad/cryptpad pull request #1674
Opened 2024-10-02 11:50 UTC by dariiing

Hello,
This PR addresses two issues related to contact request notifications:
- #1524: The contact page can now be opened via keyboard navigation when selecting the contact request notification;
- #1525: Updated the hover style to distinguish between the two events within the same notification.

2024-10-16 10:39 UTC, dariiing commented
Fix for #1524:


https://github.com/user-attachments/assets/2ee0325f-c7e1-4bcf-b578-d4d7b5ac23ac

2024-12-05 14:26 UTC, yflory requested changes

2024-12-05 14:26 UTC, yflory commented on customize.dist/src/less2/include/dropdown.less
> +            li[role="menuitem"].cp-notification-avatar {
`dropdown.less` is a generic file containing style for all dropdown in CryptPad. You shouldn't put style specific to the notifications here. `notifications.less` is more appropriate for these changes.

2024-12-10 15:15 UTC, yflory approved these changes

2024-12-12 13:00 UTC, merged