Add a `--check-only` command to `install-onlyoffice`
cryptpad/cryptpad pull request #1740
Opened 2024-12-16 06:45 UTC by jfly

This would be useful for anyone who wants to check if their OnlyOffice installation is up to date without actually installing it.

2024-12-16 07:03 UTC, jfly commented on install-onlyoffice.sh
> -    ensure_command_available unzip
I moved these checks down to right before we use the relevant tools. I'd argue this is better style (keep related things closer to gether). This is also helpful so the nix build (which installs OnlyOffice in its own way) doesn't have to depend on curl. (see https://github.com/NixOS/nixpkgs/pull/365514)

2024-12-16 09:12 UTC, wginolas requested changes
Thanks for the improvements! I found a problem that I commented in the code.

2024-12-16 09:12 UTC, wginolas commented on install-onlyoffice.sh
> +    if [ "$ACTUAL_COMMIT" != "$COMMIT" ]; then
When no OnlyOffice is installed, the script fails here, because `ACTUAL_COMMIT` is unset.

2024-12-17 10:16 UTC, jfly commented
Sure thing, @mathilde-cryptpad! I've rebased this branch.

2025-01-16 10:11 UTC, wginolas approved these changes
Looks good to me now. Thank you!

2025-03-17 14:00 UTC, merged