Fix profile layout on small screens
cryptpad/cryptpad pull request #1742
Opened 2024-12-16 15:24 UTC by DianaXWiki

2025-02-25 11:54 UTC, davidbenque commented on www/common/translations/messages.json
Please do not modify this file directly as this is handled by Weblate. Instead place new translation strings in `customize.dist/translations/messages.js` and make sure to add an `// XXX` comment on each line.

2025-02-26 11:43 UTC, davidbenque commented on www/profile/app-profile.less
> +    #cp-app-profile-rightside:has(.cp-app-profile-friend-container) #cp-app-profile-link {
Please add a comment explaining why this needs to be hidden (element was already not visible but adding extra margin to the layout)

2025-02-26 11:43 UTC, davidbenque commented on www/profile/app-profile.less
> +        margin-bottom: 1rem;
This is the expected margin bottom between buttons but other buttons are created and styled differently. You should apply the same margin-bottom to all buttons in that column. Watch out for classes that would affect all sidebar layout applications

2025-02-26 11:43 UTC, davidbenque commented on www/profile/app-profile.less
>      #cp-app-profile-description {
Please remove border and padding on `.cp-app-profile-description-rendered`

2025-02-26 11:43 UTC, davidbenque commented on www/profile/inner.js
>          APP.$descriptionEdit = $(button);
ln 452: Please move the text `p.cp-app-profile-info` to between the "view my profile" and "share" buttons as it seems more relevant

2025-02-26 11:43 UTC, davidbenque commented on www/profile/app-profile.less
> +        margin-bottom: 5rem;
margin-bottom should be 1rem here

2025-03-11 10:02 UTC, davidbenque commented
In the profile editing view there is now an issue with overlapping username and button

![image](https://github.com/user-attachments/assets/074c7265-52bc-4a7a-a379-5e13e8f53744)

2025-03-11 10:08 UTC, davidbenque requested changes
- There is an overlap issue between username and button in the edit view

![image](https://github.com/user-attachments/assets/df0b9c01-9d31-4fb8-ad19-df026ece1f9c)

- Re-requested an accessibility review from @dariiing because there are remaining issues with button icons not being hidden from screen readers

2025-03-12 11:02 UTC, dariiing reviewed
Icons have `aria-hidden`, so there isn't any issue there. However there are other problems that were not introduced with this PR:

1) Some toolbar elements in the description text box disappear on smaller screens: they are there, but not visually available. 
![image](https://github.com/user-attachments/assets/2db0a24b-6fcd-44e3-b5f2-1d8c09568be3)

![image](https://github.com/user-attachments/assets/22184aa7-d252-4b80-b512-f1522f4280f7)

If I were to use the keyboard to navigate on a smaller screen, you can see that the elements are focusable, but hidden:

https://github.com/user-attachments/assets/01a1c2e4-1fb6-4c9a-8b83-3896b515d66b

2) The text area acts as a keyboard trap; we should implement the Esc key functionality as we have in other text areas.

3) The text area breaks or expands unexpectedly while typing.

https://github.com/user-attachments/assets/1bc0d5eb-2dad-402b-a233-f73daa34e2ae

2025-03-18 16:39 UTC, yflory requested changes
Most of the comments in this review are about coding styles consistency. I didn't see anything wrong with the code itself and it should work as expected.

While testing the PR, I found one issue and I have one question.
**Issue**: on small screen, the "link" input is too large and the save button is outside the screen.
**Question/comment**: Why did you split the "view" and "share" buttons and also the rendered description and "edit" description?

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +            var $blockShare = $('<div>', {class: LINK_ID}).appendTo($container);
Same as before, LINK_ID doesn't really make sense here

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +            ).click(function () {
Using hyperscript would make it easier to write and faster to render

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        APP.$description = $('<div>', {
Please try to use hyperscript when you add or rewrite code and you don't need to jQuery tools. It's faster to render, especially on mobile.

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +
Spaces to remove here

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        var $block = $('<div>', {class: DISPLAYNAME_ID}).appendTo($container);
I don't understand this change. This makes an element and its child having the same class and applying styles to each other. I see that the class adds margins so each margin is applied twice.

2025-03-18 16:39 UTC, yflory commented on www/profile/app-profile.less
> +    div.cp-app-profile-link.hidden{
As mentioned in previous PRs, `hidden` is not a good class name as it could be used by libraries we embed in CryptPad and the style could leak to or from this library.

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        var save = h('button.btn.btn-primary', Messages.settings_save, { 'aria-labelledby': 'cp-save-link' });
We usually put the attribute object before the content. This order should work but it is a bit inconsistent with the rest of the code.

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +            id: 'cp-save-link',
Same as before, `h('input#cp-save-link', { ... })`

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +                h('i', { class: 'fa fa-address-book', 'aria-hidden': 'true' }),
Same as before about ids and classes with hyperscript. This is especially true when you modify existing code since we usually want to keep the diff as small as possible!

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +                    h('span', { id: 'cp-cancel-button' }, Messages.contacts_remove || 'Cancel Request')
Same about hyperscript and don't hesitate to break the attribute object into multiple lines when it contains multiples elements.

And I'm not sure about the translation key here. If I understand/remember the code correctly, this is a button to cancel a contact request that has not been accepted yet. It was changed from "cancel" to "contacts_remove" but I don't understand why.
You should also remove the hardcoded value here: it's adding unnecessary bytes to the file and if you do so when adding a new key, we may skip that translation key and never notice that it's missing until we test with a different language. There may be some places in the code that still have such hardcoded translation but we want to avoid/remove them with our new processes.

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +                        h('span', { id: 'cp-unmute-button' }, Messages.contacts_unmute || 'Unmute')
In multiple places you added similar ids. I don't think they will create issue here but be careful with generic names, even when you use the `cp-` prefix.
"cp-cancel-button", "cp-unmute-button", etc. are names that could be used in the rest of the product and we could accidentally apply styles here when modifying something else. Usually we try to add the application in the name when describing a very specific element: "cp-profile-cancel-button"

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +            title: Messages.profile_remove_avatar //XXX
No need for XXX here if you've already added the temporary key to customize.dist/messages.js

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        editor.on("keydown", function (cm, event) {
CodeMirror directly includes a way to handle keyboard events:
```javascript
editor.setOption("extraKeys", {
    "Esc": function () {
        cm.getInputField().blur();
        $(save).focus();
    }
}
```
This would avoid any conflict with other shortcuts that can be added.

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        if ($.trim(descriptionData) === "") {
It's probably faster to use the native "trim" instead of jQuery: `descriptionData.trim()`

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +        ).append(
You can append multiple elements with jQuery using an array:
```javascript
$something.append([
  element1,
  element2
])

2025-03-18 16:39 UTC, yflory commented on www/profile/inner.js
> +            ])).click(function () {
Multiple indentations and coding style inconsistencies here
```
APP.$copyData = $(h('button.btn.btn-secondary', {
    'aria-labelledby': '...'
}, [
  h('i.fa.fa-clipboard', { ... }),
  h('span#cp-copy-data-button', ...)
]).click(function () {
```

2025-03-24 11:08 UTC, yflory approved these changes

2025-03-24 15:20 UTC, merged